namespace :files do
 desc 'rename received file suffix from yaml to yml'
 task :rename_yaml, [:file, :path] do |t, args|
   raise "No file name received"                      unless args.file
   raise "File #{args.file} is not of yaml type"      unless File.extname(args.file) == ".yaml"
   path_expd = "#{File.expand_path(args.path)}/"
   raise "File #{path_expd}#{args.file} is not valid" unless File.file?("#{path_expd}#{args.file}")
   file_base = File.basename(args.file,".yaml")
   raise "File #{file_base}.yml already exists"       if File.exist?("#{path_expd}#{file_base}.yml")
   File.rename("#{path_expd}#{args.file}","#{path_expd}#{file_base}.yml")
   puts "File #{path_expd}#{args.file} renamed to #{path_expd}#{file_base}.yml"
 end
end
